### ISSUE TITLE
Cannot delete transaction

### ISSUE THREAD

**Issue by PrzemekSkw** [IndomaximTechID/storaji#7]
I made a mistake and want to delete transaction, I delete customer and product but transaction is still on. Now when I click on Transactions window looks like that:
![zrzut ekranu deepin_20180112124542](https://user-images.githubusercontent.com/25219988/34873798-d652fa28-f796-11e7-986f-4ee1df8c1b04.png)

**Comment by lowsprofile** [comment]
@PrzemekSkw When you see bug looks like above again, try navigate to View Menu >  Toggle Developer Options. And please tell us what is showed on the console bar, so we can track what really happens there.

**Comment by PrzemekSkw** [comment]
When I click Reports > Orders i see that bug. In developers console there's that output:
![zrzut ekranu z 2018-01-12 18-13-27](https://user-images.githubusercontent.com/25219988/34886767-700542c0-f7c4-11e7-8471-00eeb2059a11.png)

**Comment by lowsprofile** [comment]
@PrzemekSkw It was an Elements bar in the screenshot, can you click the Console and do screenshot there? :smiley:

**Comment by lowsprofile** [comment]
This was fixed on 22d0922
Consider to the rule, you can't delete the transaction log whatever you have done.
But in storaji the original data was not deleted permanently such as product and customer data. So in this case, I have able to show the log with related product and customer even if they are all deleted.

In the future, I will create Junk Section for managing the data back to be able again. :beers:

**Comment by PrzemekSkw** [comment]
It works now when I open Storaji today :), thanks. But still have that transaction.

**Comment by lowsprofile** [comment]
> It works now when I open Storaji today :), thanks. But still have that transaction.

Ability to delete order is available on v1.0.0-beta.5 on commit 3a7f735  and will be released after build process and test are passing from [travisci](https://travis-ci.org/IndomaximTechID/storaji-ui) and [appveyor](https://ci.appveyor.com/project/lowsprofile/storaji-ui).

And the app should notify if latest release is available when you check for updates or open the app first time. Please if the feature works well after updating the app don't forget to close this issue. Thanks :beers:

**Comment by PrzemekSkw** [comment]
Thanks, cheers 🍻
